<?php
/**
 * @author rohith.mohan@equifax.com
 * @copyright ReachTel (ABN 40 133 677 933)
 */

namespace Services\Utils;

/**
 * Class ActivityLoggerActions
 */
class ActivityLoggerActions
{
    const ACTION_CAMPAIGN_EMPTY = 'CAMPAIGNEMPTY';
    const ACTION_CAMPAIGN_ARCHIVE_TARGETS = 'CAMPAIGNARCHIVETARGETS';
    const ACTION_CAMPAIGN_DELETE = 'CAMPAIGNDELETE';
    const ACTION_CAMPAIGN_SAVE_SETTINGS = 'CAMPAIGNSAVESETTINGS';
    const ACTION_CAMPAIGN_RESET_READY = 'CAMPAIGNRESETREADY';
    const ACTION_CAMPAIGN_UPLOAD_DATA = 'CAMPAIGNUPLOADDATA';
    const ACTION_UPDATE_SETTINGS = 'UPDATESETTINGS';
    const ACTION_REMOVE_SETTINGS = 'REMOVESETTINGS';
    const ACTION_DOWNLOAD_CAMPAIGN_REPORT = 'CAMPAIGNDOWNLOADREPORT';
    const ACTION_FAILED_DOWNLOAD_CAMPAIGN_REPORT = 'CAMPAIGNDOWNLOADREPORTFAILED';
    const ACTION_CAMPAIGN_TARGET_REMOVE = 'CAMPAIGNTARGETREMOVE';
}
