<p style="float: left; height: 200px; width: 250px; text-align: center;">{if $targets_results.GENERATED == 0}None sent{else}<img src="//chart.googleapis.com/chart?cht=p&chs=250x200&chco=269e01|e94e15|cccc33|068dc7&chd=t:{if $targets_status.TOTAL > 0}{math|string_format:"%01.1f"|default:"0" equation="(open/total)*100" open=$email.TRACK total=$targets_status.TOTAL}{else}0.0{/if},{if $targets_status.TOTAL > 0}{math|string_format:"%01.1f"|default:"0" equation="((hard+soft)/total)*100" hard=$email.HARDBOUNCE soft=$email.SOFTBOUNCE total=$targets_status.TOTAL}{else}0.0{/if},{if $targets_status.TOTAL > 0}{math|string_format:"%01.1f"|default:"0" equation="((bounced+duplicate+unsubscribed)/total*100)" bounced=$email.BOUNCED duplicate=$email.DUPLICATE unsubscribed=$email.UNSUBSCRIBED total=$targets_status.TOTAL}{else}0.0{/if},{if $targets_status.TOTAL > 0}{math|string_format:"%01.1f"|default:"0" equation="(1-((open+hard+soft+bounced+duplicate+unsubscribed)/total))*100" open=$email.TRACK total=$targets_status.TOTAL hard=$email.HARDBOUNCE soft=$email.SOFTBOUNCE bounced=$email.BOUNCED duplicate=$email.DUPLICATE unsubscribed=$email.UNSUBSCRIBED}{else}0.0{/if}" alt="chart" title="chart" style="width: 250px; height: 200px;" />{/if}</p>
<p>
  {math assign="total1" equation='total - (dnc+hard+soft+bounced+duplicate+unsubscribed)' total=$targets_status.TOTAL dnc=$email.DNC hard=$email.HARDBOUNCE soft=$email.SOFTBOUNCE bounced=$email.BOUNCED duplicate=$email.DUPLICATE unsubscribed=$email.UNSUBSCRIBE}
  {math assign="total2" equation='targets - abandoned' targets=$targets_status.TOTAL abandoned=$targets_status.ABANDONED}
  <span style="background: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{$targets_status.TOTAL|default:"0"} recipients loaded<br />
  <span style="background: #cccc33;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if $targets_status.TOTAL > 0}{math|string_format:"%01.1f"|default:"0" equation="((dnc+duplicate)/total*100)" duplicate=$email.DUPLICATE dnc=$email.DNC total=$targets_status.TOTAL}{else}0.0{/if}% of recipients previously unsubscribed, bounced or were duplicates. <span class="subtext">({math|default:"0" equation="dnc+duplicate" duplicate=$email.DUPLICATE dnc=$email.DNC} recipients removed)</span><br />
  <span style="background: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if (total2 > 0) AND ($targets_results.GENERATED > 0)}{math|string_format:"%01.0f"|default:"0" equation="(events/total)*100" events=$targets_results.GENERATED total=total2}{else}0.0{/if}% of the emails have been sent. <span class="subtext">({$targets_results.GENERATED|default:"0"} emails sent)</span><br />
  <br />
  <span style="background: #e94e15;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if $targets_results.GENERATED > 0}{math|string_format:"%01.1f"|default:"0.0" equation="((hard+soft)/total)*100" hard=$email.HARDBOUNCE soft=$email.SOFTBOUNCE total=$targets_results.GENERATED}{else}0.0{/if}% of sent emails bounced. <span class="subtext">({$email.HARDBOUNCE+$email.SOFTBOUNCE|default:"0"} were returned to us undelivered)</span><br />
  <span style="background: #068dc7;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if total1 > 0}{math|string_format:"%01.1f"|default:"0" equation="(1-(open/total1))*100" open=$email.TRACK total=total1}{else}0.0{/if}% of delivered recipients not opened. <span class="subtext">({if $targets_status.TOTAL > 0}{math|default:"0" equation="(total - (dnc+open+hard+soft+bounced+duplicate+unsubscribed))" dnc=$email.DNC open=$email.TRACK total=$targets_status.TOTAL hard=$email.HARDBOUNCE soft=$email.SOFTBOUNCE bounced=$email.BOUNCED duplicate=$email.DUPLICATE unsubscribed=$email.UNSUBSCRIBED}{else}0{/if} still unopened)</span><br />
  <span style="background: #269e01;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if total1 > 0}{math|string_format:"%01.1f"|default:"0" equation="(open/total1)*100" open=$email.TRACK total=total1}{else}0.0{/if}% of delivered recipients opened the email. <span class="subtext">({$email.TRACK|default:"0"} unique opens)</span><br />
  <br />
  <span style="background: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if total1 > 0}{math|string_format:"%01.1f"|default:"0" equation="(clicked/total1)*100" clicked=$email.CLICK total=total1}{else}0.0{/if}% of delivered recipients clicked a link. <span class="subtext">({$email.CLICK|default:"0"} recipients)</span><br />
  <span style="background: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;{if total1 > 0}{math|string_format:"%01.1f"|default:"0" equation="(unsubscribed/total1)*100" unsubscribed=$email.UNSUBSCRIBE total=total1}{else}0.0{/if}% of delivered recipients unsubscribed. <span class="subtext">({$email.UNSUBSCRIBE|default:"0"} recipients)</span><br />
</p>
